server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
      druid:
        one:
          url: jdbc:mysql://localhost:13306/test
          username: root
          password: 4321
        two:
          url: jdbc:mysql://localhost:13306/test2
          username: root
          password: 4321
