server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:13306/test
    username: root
    password: 4321
    driver-class-name: com.mysql.jdbc.Driver

secondary:
  datasource:
    url: jdbc:mysql://localhost:13306/test2
    username: root
    password: 4321
    driver-class-name: com.mysql.jdbc.Driver
